### ISSUE TITLE
canal stable dépassé

### ISSUE THREAD

**Issue by brol** [franck-paul/sysInfo#13]
coucou,
v3.2, dc 2.26-dev-r20230213.1759, wamp64

c'est bizarre d'avoir des infos aussi vieilles pour la version stable, non ? cf image jointe
![Screenshot 2023-02-14 at 02-02-15 Informations système - labodc2 - Dotclear - 2 26-dev-r20230213 1759](https://user-images.githubusercontent.com/5787951/218611596-87ac0777-04c4-474a-8e3c-6504b652d0be.png)

**Comment by brol** [comment]
depuis le plugin mise à jour, j'ai cliqué sur le bouton "Forcer la vérification de mise à jour de Dotclear" puis suis retourné dans sysinfo 3.2.1. pas de changement. j'ai supprimé à la mimine le fichier dotclear-stable dans version, puis retour sur mise à jour, re forcer... et le fichier ne s'est pas recréé, du coup, n'est listée que la version unstable dans le plugin. 
si tu veux d'autres manips, tu me dis.

**Comment by franck-paul** [comment]
Donc tout va bien, sysInfo ne fait que lire ce qui existe dans le cache.
