### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by JcDenis** [franck-paul/sysInfo#14]
Il serait sympa que ce plugin puisse sortir un ou plusieurs rapports (avec obfuscation de données sensibles), ça pourrait devenir à terme un outil d'aide pour rapporter des bugs. cf ticket sur les _issue template_

**Comment by franck-paul** [comment]
Yup, j'y ai pensé une fois ou deux, je garde sous le coude pour faire ça un jour ou l'autre ;-)

**Comment by franck-paul** [comment]
Voilà, 3.6 publiée, on verra s'il y a besoin d'autre chose plus tard…
