### ISSUE TITLE
zip introuvable

### ISSUE THREAD

**Issue by JcDenis** [franck-paul/sysInfo#5]
Coquille dans la génération de dcstore.xml, le fichier contient :
https://github.com/franck-paul/sysInfo/releases/download/1.15.1/plugin-sysInfo-1.15.2.zip
alors que le zip se trouve la :
https://github.com/franck-paul/sysInfo/releases/download/1.15.2/plugin-sysInfo-1.15.2.zip

**Comment by franck-paul** [comment]
Hi hi, la mécanique du cerveau n'est pas encore en place :-)

**Comment by franck-paul** [comment]
Bah non j'ai poussé correctement, sauf qu'entretemps la branche master a changé de nom pour main

**Comment by franck-paul** [comment]
Arf j'ai pas tout lu, my bad! Je fix…
