### ISSUE TITLE
Fatal error with php8.1 and Closure on Behaviors

### ISSUE THREAD

**Issue by JcDenis** [franck-paul/sysInfo#7]
Sous php 8.1(.1) si un behavior utlise une function anonyme (Closure), le plugin sysInfo plante.

`Fatal error: Uncaught Error: Object of class Closure could not be converted to string in /var/www/dc/plugins/sysInfo/inc/lib.sysinfo.php:215`

Il va falloir prendre en compte ce type de behaviors.

**Comment by franck-paul** [comment]
Oui j'ai vu ça hier, pas encore poussé de nouvelle release mais ça va venir :-)
